### ISSUE TITLE
function pointers

### ISSUE THREAD

**Issue by dherman** [asm-js/validator#4]
Add support for function pointers.

**Comment by rntz** [comment]
I've just looked at the asm.js spec at http://asmjs.org/spec/latest/#value-types , and there is no provision for function pointers as values. Why was this closed?

**Comment by sunfishcode** [comment]
What was added was support for function tables:

http://asmjs.org/spec/latest/#function-table-types

Function tables and indices thereinto can provide function-pointer functionality.
